version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 9001:9001
    links:
      - postgresql
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresql
    image: postgres:9.6.5-alpine
    environment:
      POSTGRES_DB: teaching_app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: for_pony
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume: